name: CI Build

env:
  Product: QuickEPUB
  BinDir: ./src/QuickEPUB/bin
  SolutionFile: ./src/QuickEPUB.sln

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: pwsh

jobs:
  ci_build:
    name: CI Build and Test
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Solution
      run: dotnet build --configuration ${{ matrix.configuration }} ${{ env.SolutionFile }}

    - name: Test Solution
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build ${{ env.SolutionFile }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.Product }}${{ matrix.configuration }}Binaries
        path: ${{ env.BinDir }}/${{ matrix.configuration }}/
